Add fetch hook and modal components
Basnor/react-burger pull request #3
Opened 2023-02-08 19:09 UTC by Basnor

2023-02-09 05:57 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами и правильно используете `useEffect` и `useCallback`.

Есть только один момент, который необходимо исправить.

Необходимо исправить:
- Добавьте проверку успешности запроса.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарий с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-09 05:57 UTC, andryxxa93 commented on src/hooks/useFetch.tsx
> +      const response = await fetch(url).then((res) => res.json());
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)


```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-02-09 05:57 UTC, andryxxa93 commented on src/components/modal/modal.tsx
> +      document.removeEventListener("keydown", onKeyDown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-02-09 05:57 UTC, andryxxa93 commented on src/components/modal/modal.tsx
> +}
**Можно лучше**
Каждый новый компонент лучше выносить в отдельный файл - это упрощает чтение кода и его расширение.

2023-02-11 05:33 UTC, Basnor commented on src/components/modal/modal.tsx
> +}
Я бы пока оставила. Компонент ModalOverlay небольшой и его расширение маловероятно.
По остальным компонентам учту этот момент в будущем, по мере их разрастания.

2023-02-11 08:52 UTC, Basnor commented on src/hooks/useFetch.tsx
> +      const response = await fetch(url).then((res) => res.json());
Я провела эксперимент. Попыталась получить данные с несуществующего адреса. Приложение не упало, в консоли 404. Все верно. 
Затем, попробовала залогировать, попадаю ли я в catch. Попадаю, но прикол в том, что пойманная ошибка - SyntaxError.
![Screenshot from 2023-02-11 15-12-48](https://user-images.githubusercontent.com/25279084/218247904-fd8e04e2-593f-4435-b386-12c7b32eb741.png)

Выводы такие: если нам нужна понятная ошибка, нужно ее записывать сразу после получения ответа от fetch.

2023-02-11 09:32 UTC, andryxxa93 commented on src/hooks/useFetch.tsx
> +      const response = await fetch(url).then((res) => res.json());
Вы получали такую ошибку потому что при попытке обратиться к несуществующему адресу сервер отвечает не `json` объектом а `html` страницей `404.` Это видно на скриншоте. Если нет проверки на `response.ok` тогда к такому ответу код пытается применить метод `json` - получается ошибка синтаксическая и конечно `try` отсылает в `catch`. Но такой подход как вы правильно заметили не даёт верное представление об ошибке. 

<img width="1440" alt="Снимок экрана 2023-02-11 в 12 22 52" src="https://user-images.githubusercontent.com/60173362/218250881-1ab58b0a-0e27-46f1-a09a-4797df47ee1b.png">

2023-02-11 09:48 UTC, andryxxa93 approved these changes
Отличная работа! Всё сделано правильно, удачного вам продолжения обучения.

2023-02-12 08:57 UTC, merged