Add websocket feeds
Basnor/react-burger pull request #8
Opened 2023-04-16 14:03 UTC by Basnor

2023-04-16 16:26 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая типизация
- Есть таймер переподключения сокета
- Хорошая работа с датами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Необходимо подсчитывать количество повторяющихся ингредиентов в заказе и увеличивать их счетчик. У вас сейчас у всех ингредиентов стоит - 1х. 
- В разделе "Готовится" не появляется номер заказа, хотя по сокету он приходит.
 
<img width="986" alt="Снимок экрана 2023-04-16 в 19 15 50" src="https://user-images.githubusercontent.com/60173362/232326018-9590e2b9-d3b3-41cb-9daf-44dd2f5ef30a.png">

- Сокет соединение необходимо закрывать при уходе со страницы "История заказов". Сейчас закрывается только при уходе со страницы профиля.
- У вас в `IngredientItem` есть тип `any` в пропсах компонента - там от него можно без проблем избавиться. 

**Можно лучше**
- Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей. Иначе сейчас при заходе на страницу "История заказов" сначала на пару секунд видно данные из "Ленты заказов".
- 

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-16 16:26 UTC, andryxxa93 commented on src/services/socket-middleware.ts
> +        socket.onmessage = (event: MessageEvent) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-04-17 17:14 UTC, Basnor commented
Добавила сброс состояния при разрыве сокет соеденения, теперь данные не накладываются и можно не разделять хранилище.

2023-04-17 17:16 UTC, Basnor commented
> Здравствуйте! Проделана большая работа +1
> 
> Что понравилось:
> 
> * Хорошая типизация
> * Есть таймер переподключения сокета
> * Хорошая работа с датами
> 
> Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.
> 
> Необходимо исправить:
> 
> * Необходимо подсчитывать количество повторяющихся ингредиентов в заказе и увеличивать их счетчик. У вас сейчас у всех ингредиентов стоит - 1х.
> * В разделе "Готовится" не появляется номер заказа, хотя по сокету он приходит.
> 
> <img alt="Снимок экрана 2023-04-16 в 19 15 50" width="986" src="https://user-images.githubusercontent.com/60173362/232326018-9590e2b9-d3b3-41cb-9daf-44dd2f5ef30a.png">
> 
> * Сокет соединение необходимо закрывать при уходе со страницы "История заказов". Сейчас закрывается только при уходе со страницы профиля.
> * У вас в `IngredientItem` есть тип `any` в пропсах компонента - там от него можно без проблем избавиться.
> 
> **Можно лучше**
> 
> * Нужно организовать раздельное хранение данных в хранилище Redux, получаемых от сокета для авторизованного и неавторизованного пользователей. Иначе сейчас при заходе на страницу "История заказов" сначала на пару секунд видно данные из "Ленты заказов".
> 
> В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.
> 
> **Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.
> 
> Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью.
> 
> Удачных правок!

Добавила сброс состояния при разрыве сокет соеденения, теперь данные не накладываются и можно не разделять хранилище.

2023-04-17 17:24 UTC, Basnor commented on src/services/feed.tsx
> +        state.totalToday = 0;
Добавила сброс состояния при разрыве сокет соеденения, теперь данные не накладываются и можно не разделять хранилище.

2023-04-17 17:29 UTC, Basnor commented on src/services/socket-middleware.ts
> +        socket.onmessage = (event: MessageEvent) => {
Добавила сброс состояния при разрыве сокет соеденения, теперь данные не накладываются и можно не разделять хранилище.

2023-04-18 05:55 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-20 13:52 UTC, merged